version: "3.7"

services:
  db_cyber2:
    image: mariadb:10.5
    container_name: db_cyber2
    networks:
      - my_network
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: cyber2
      MARIADB_USER: admin
      MARIADB_PASSWORD: P@$$w0rd
    volumes:
      - db_data:/var/lib/mysql               # Persistance des données
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Script d'initialisation
    ports:
      - "3306:3306"

  web_cyber2:
    build: ./web
    container_name: php_cyber2
    depends_on:
      - db_cyber2
    networks:
      - my_network
    ports:
      - "80:80"
    environment:
      DB_HOST: db_cyber2
      DB_NAME: cyber2
      DB_USER: admin
      DB_PASSWORD: P@$$w0rd

networks:
  my_network:
    driver: bridge
volumes:
  db_data: